"""parents association table

Revision ID: dac14e4a592f
Revises: e01a91c0b16e
Create Date: 2018-03-21 14:22:47.736997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac14e4a592f'
down_revision = 'e01a91c0b16e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parents',
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['user.id'], )
    )
    op.drop_table('supergoals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supergoals',
    sa.Column('supergoal_id', sa.INTEGER(), nullable=True),
    sa.Column('subgoal_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['subgoal_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['supergoal_id'], ['user.id'], )
    )
    op.drop_table('parents')
    # ### end Alembic commands ###
